on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.azureCredentials }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n cloudregistry1 -g cloudregistry1b73e-rg --location "West US 2" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n cloudregistry1 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n cloudregistry1 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n cloudregistry1 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: cloudregistry1.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/corona-app-v1" -f  "corona-app-v1/Dockerfile" -t cloudregistry1.azurecr.io/kubernetes:${{ github.sha }}
        docker push cloudregistry1.azurecr.io/kubernetes:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_kubernetes_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kubernetesa1e0 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kubernetesa1e0`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kubernetesa1e0
        container-registry-url: cloudregistry1.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: kubernetesdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: kubernetesa1e0
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
          manifests/ingress.yml
        images: |
          cloudregistry1.azurecr.io/kubernetes:${{ github.sha }}
        imagepullsecrets: |
          kubernetesdockerauth