on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: maindockedrregistry.azurecr.io
        username: ${{ secrets.acr_maindockedrregistry_username }}
        password: ${{ secrets.acr_maindockedrregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/corona-app-v1" -f  "corona-app-v1/Dockerfile" -t maindockedrregistry.azurecr.io/main:${{ github.sha }}
        docker push maindockedrregistry.azurecr.io/main:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_main_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep main726d | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace main726d`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: main726d
        container-registry-url: maindockedrregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_maindockedrregistry_username }}
        container-registry-password: ${{ secrets.acr_maindockedrregistry_password }}
        secret-name: maindockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: main726d
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          maindockedrregistry.azurecr.io/main:${{ github.sha }}
        imagepullsecrets: |
          maindockerauth