on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: coviddashacr.azurecr.io
        username: ${{ secrets.acr_coviddashacr_username }}
        password: ${{ secrets.acr_coviddashacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/corona-app-v1" -f  "corona-app-v1/Dockerfile" -t coviddashacr.azurecr.io/kcluster:${{ github.sha }}
        docker push coviddashacr.azurecr.io/kcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kcluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kclusterf964 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kclusterf964`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kclusterf964
        container-registry-url: coviddashacr.azurecr.io
        container-registry-username: ${{ secrets.acr_coviddashacr_username }}
        container-registry-password: ${{ secrets.acr_coviddashacr_password }}
        secret-name: kclusterdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: kclusterf964
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          coviddashacr.azurecr.io/kcluster:${{ github.sha }}
        imagepullsecrets: |
          kclusterdockerauth